name: Test storybook

on:
  workflow_call:

jobs:
  test-storybook:
    name: Test storybook
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@caching
        with:
          should-cache-restore: ${{ vars.USE_CACHING }}

      - name: Install Playwright browsers
        run: yarn exec playwright install chromium

      - name: Test Storybook
        run: yarn test-storybook:ci
